# Generated by Django 3.2.8 on 2021-11-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(default='', max_length=8)),
            ],
        ),
    ]
