# Generated by Django 3.2.8 on 2021-11-12 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP3', '0002_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='clean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=25)),
                ('img', models.ImageField(null=True, upload_to='media')),
                ('price', models.PositiveIntegerField(default=None)),
                ('description', models.TextField(null=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP3.type')),
            ],
        ),
    ]
