# Generated by Django 3.2.8 on 2021-11-13 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP3', '0006_mycart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycart',
            name='update_on',
        ),
    ]
