# Generated by Django 3.2.8 on 2021-11-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP3', '0007_remove_mycart_update_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycart',
            name='add_on',
        ),
        migrations.AddField(
            model_name='mycart',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
