# Generated by Django 3.2.8 on 2021-11-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP3', '0008_auto_20211113_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=25)),
                ('services', models.CharField(default='', max_length=50)),
                ('adddress', models.CharField(default='', max_length=100)),
                ('contact', models.CharField(default='', max_length=11)),
                ('service_date', models.DateField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField(default=None)),
            ],
        ),
    ]
