# Generated by Django 3.2.8 on 2021-11-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP3', '0010_rename_order_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='oemail',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
