# Generated by Django 3.2.8 on 2021-11-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP3', '0011_orders_oemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
