# Generated by Django 3.2.8 on 2021-11-27 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP3', '0014_alter_orders_service_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='placed_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 27, 11, 38, 1, 156647)),
        ),
    ]
